name: mercor-dominicks-acquisition-analysis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - pytest
  - pip:
    - python-dotenv
    - awscli
    - -e .